name: Monitoring Notification

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Health Check
        run: |
          if grep -q "Stable" live/index.html
          then
            echo "Application Healthy"
          else
            echo "Health Check Failed"
            exit 1
          fi

      - name: Send Success Message
        if: success()
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"✅ Deployment Successful\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Failure Message
        if: failure()
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"❌ Deployment Failed\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}